//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ExecutionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExecutionService.iExecitionService")]
    public interface iExecitionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iExecitionService/Compile", ReplyAction="http://tempuri.org/iExecitionService/CompileResponse")]
        string Compile(string programm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iExecitionService/Compile", ReplyAction="http://tempuri.org/iExecitionService/CompileResponse")]
        System.Threading.Tasks.Task<string> CompileAsync(string programm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iExecitionServiceChannel : Client.ExecutionService.iExecitionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iExecitionServiceClient : System.ServiceModel.ClientBase<Client.ExecutionService.iExecitionService>, Client.ExecutionService.iExecitionService {
        
        public iExecitionServiceClient() {
        }
        
        public iExecitionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iExecitionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iExecitionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iExecitionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Compile(string programm) {
            return base.Channel.Compile(programm);
        }
        
        public System.Threading.Tasks.Task<string> CompileAsync(string programm) {
            return base.Channel.CompileAsync(programm);
        }
    }
}
